# Generated by Django 2.2 on 2021-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=200, verbose_name='Department/Office')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP Address')),
                ('gateway', models.CharField(max_length=200, verbose_name='Gateway Address')),
                ('device', models.CharField(max_length=200, verbose_name='Device Assigned')),
                ('configured', models.CharField(max_length=200, verbose_name='Configured by')),
                ('date', models.DateField(verbose_name='Date Configured')),
            ],
        ),
    ]
