# Generated by Django 2.2 on 2021-07-22 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0002_network_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='remarks',
        ),
    ]
