# Generated by Django 2.2 on 2021-07-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0003_remove_network_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='remarks',
            field=models.CharField(default='Enter comments', max_length=200, verbose_name='Comments'),
        ),
    ]
