# Generated by Django 2.2 on 2021-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0004_network_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='remarks',
            field=models.CharField(default=False, max_length=200, verbose_name='Comments'),
        ),
    ]
