# Generated by Django 2.2 on 2021-07-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0005_auto_20210722_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='remarks',
            field=models.CharField(default='Please provide comments', max_length=200, verbose_name='Comments'),
        ),
    ]
