# Generated by Django 2.2 on 2021-07-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0007_auto_20210722_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='remarks',
            field=models.CharField(max_length=500, verbose_name='Comments'),
        ),
    ]
