# Generated by Django 2.2 on 2021-07-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0008_auto_20210728_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='images',
            field=models.ImageField(default=False, upload_to='images/'),
            preserve_default=False,
        ),
    ]
