# Generated by Django 2.2 on 2021-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0009_network_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
