# Generated by Django 2.2 on 2021-08-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0010_auto_20210729_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
