# Generated by Django 2.2 on 2021-08-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracker', '0011_auto_20210802_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='office',
            field=models.CharField(max_length=200, verbose_name='Department'),
        ),
    ]
